DROP TABLE IF EXISTS "realty_data_raw";
CREATE TABLE "realty_data_raw" (
  "ID ЖК" BIGINT,
  "ЖК рус" BIGINT,
  "ЖК англ" TEXT,
  "Район Город" TEXT,
  "Округ Направление" TEXT,
  "Регион" TEXT,
  "АТД" TEXT,
  "Застройщик ЖК" TEXT,
  "Описание помещения" TEXT,
  "Площадь" DOUBLE PRECISION,
  "Комнатность" BIGINT,
  "Тип Комнатности" BIGINT,
  "Этаж" BIGINT,
  "Номер" TEXT,
  "Тип помещения" TEXT,
  "Корпус" TEXT,
  "Покупатель ЮЛ" TEXT,
  "Покупатель ФЛ" BIGINT,
  "Номер регистрации" TEXT,
  "Дата регистрации" TIMESTAMP,
  "Условия обременения" TEXT,
  "Номер обременения" TEXT,
  "Дата обременения" TIMESTAMP,
  "Залогодержатель" TEXT,
  "Длительность обременения" BIGINT,
  "Тип обременения" TEXT,
  "Оценка цены" BIGINT,
  "Реквизиты ДДУ" TEXT,
  "Дата ДДУ" TIMESTAMP,
  "Конец месяца ДДУ" TIMESTAMP,
  "Год ДДУ" BIGINT,
  "Уступка" BIGINT,
  "Купил лотов в ЖК" BIGINT,
  "ID Корпус" BIGINT,
  "Пол" TEXT,
  "класс" TEXT,
  "Срок сдачи" TEXT,
  "Ввод" BIGINT,
  "Стадия строительства" TEXT,
  "lat" DOUBLE PRECISION,
  "lng" DOUBLE PRECISION,
  "Ипотека" BIGINT,
  "Секция" TEXT,
  "Отделка" TEXT,
  "Старт продаж К" DOUBLE PRECISION,
  "Продавец ЮЛ" TEXT,
  "Продавец ФЛ ID" BIGINT,
  "Зона" TEXT,
  "Купил кв и ап в ЖК" BIGINT,
  "Стадия строительства в дату ДДУ" TEXT,
  "Цена ДДУ" BIGINT,
  "Цена ДДУ Есть/Нет" TEXT,
  "Цена со скидкой" BIGINT,
  "Цена со скидкой или без" BIGINT,
  "Наличие цены со скидкой или без" TEXT,
  "Тип сделки" TEXT,
  "Тип оценки" TEXT,
  "Разница дат" BIGINT,
  "Дата регистрации модель" TIMESTAMP,
  "version" BIGINT,
  "Участок" TEXT,
  "ФИО" TEXT,
  "Цена кв. м" BIGINT,
  "ID дом.рф" BIGINT,
  "ИНН ЮЛ" TEXT,
  "Год рожд." BIGINT,
  "Оценка по ЕИСЖС" TEXT
);
